// PLACEHOLDER -- generated by hand, not by the FlutterFire CLI.
//
// Run `flutterfire configure` from the project root once you have a
// Firebase project set up; it will OVERWRITE this file with your project's
// real values (see FLUTTER_UPDATE_mood_emoji_and_fcm.md in the backend repo
// for the full walkthrough). Until then, PushService detects these
// placeholder values and skips Firebase entirely -- the app runs normally,
// just without push notifications, exactly like the backend no-ops when
// FIREBASE_CREDENTIALS_PATH isn't set.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

const String kFirebasePlaceholderMarker = 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for android and ios in this project.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOUjE9DQMls1X08Itb9T_qTTHuxiXwLT4',
    appId: '1:950963564511:android:b73b090c56cfd62c159e6a',
    messagingSenderId: '950963564511',
    projectId: 'speechtotext-dceb9',
    storageBucket: 'speechtotext-dceb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: kFirebasePlaceholderMarker,
    appId: kFirebasePlaceholderMarker,
    messagingSenderId: kFirebasePlaceholderMarker,
    projectId: kFirebasePlaceholderMarker,
    iosBundleId: 'com.throughline.throughline',
  );
}
